Feature/ms 477 update invoices endpoint
coverwallet/cw-node-public-api-sdk pull request #17
Opened 2022-08-04 15:16 UTC by AlvaroGV

2022-08-04 15:18 UTC, AlbertHernandez requested changes

2022-08-04 15:18 UTC, AlbertHernandez commented on src/cwApi.ts
> +            account_id: string;
I think we should not have this property

2022-08-04 15:25 UTC, AlvaroGV commented on src/cwApi.ts
> +            account_id: string;
Yeah, this will be deleted once we upload swagger

2022-08-05 06:05 UTC, dmitry-naumchik-cw approved these changes

2022-08-05 08:43 UTC, AlbertHernandez reviewed
Like we are changing the interface of the methods, I think this should be a major version

2022-08-05 09:24 UTC, AlbertHernandez approved these changes

2022-08-05 09:26 UTC, merged